"""
Vocabulário auxiliar (prompt) para transcrição de laudos/exames por voz com Whisper.

A API da OpenAI limita o campo ``prompt`` do Whisper a **no máximo 224 tokens**;
se o texto exceder esse limite, **apenas os últimos 224 tokens** são considerados
(guia OpenAI). Por isso ``build_exam_whisper_prompt`` concatena **termos de menor
prioridade primeiro** e **os mais críticos por último**, e aplica truncagem
conservadora por ``max_chars`` (~224 tokens sem depender de tiktoken), preservando
o **sufixo** da string.

Não incluir nomes de pacientes, instituições ou outros identificadores (LGPD).
"""

from __future__ import annotations

import os
import re
from typing import List

# --- Prioridade baixa (contexto geral / administrativo de exame, sem PII) ---
_CHUNKS_LOW: List[str] = [
    "exame laboratorial",
    "resultado de exame",
    "material recebido",
    "data da coleta",
    "data do exame",
    "unidade",
    "método",
    "metodologia",
    "observação",
    "nota técnica",
    "assinado digitalmente",
    "amostra adequada",
    "amostra insuficiente",
    "controle de qualidade",
    "repetir coleta",
    "jejum",
    "urina jato médio",
    "urina recente",
    "primeira urina da manhã",
    "sangue periférico",
    "sangue venoso",
    "plasma",
    "soro",
    "soro gel separado",
    "tubo com EDTA",
    "tubo seco",
    "tubo citrato",
    "hemólise",
    "lipêmico",
    "icterícia",
    "turva",
    "pediatria",
    "neonatologia",
    "recém-nascido",
    "idade gestacional",
    "pré-natal",
    "pós-parto",
    "puérpera",
    "gestante",
    "trimestre da gestação",
    "coleta capilar",
    "coleta arterial",
    "gasometria capilar",
    "oximetria de pulso",
    "curva de tolerância",
    "teste oral de tolerância à glicose",
    "medicina transfusional",
    "fenotipo eritrocitário",
    "fenotipo estendido",
    "anticorpos irregulares",
    "painel de fenotipagem",
    "crossmatch",
    "compatibilidade transfusional",
    "reserva de sangue",
    "bolsa de concentrado de hemácias",
    "bolsa de plaquetas",
    "bolsa de plasma",
    "crioprecipitado",
    "imunização antenatal",
    "imunização pós-exposição",
    "carteira de vacinação",
    "caderneta da criança",
    "teste rápido",
    "autoteste",
    "protocolo de coleta",
    "cadastro de exame",
    "solicitação médica",
    "guia de encaminhamento",
    "laboratório de apoio",
    "amostra biológica",
    "transporte refrigerado",
    "cadeia de frio",
    "líquido ascítico",
    "líquido pleural",
    "punção guiada",
    "drenagem torácica",
    "paracentese",
    "citologia em meio líquido",
    "LBC",
    "colpocitologia oncótica",
    "raspado cervical",
    "teste molecular point-of-care",
    "relatório preliminar",
    "laudo complementar",
    "revisão técnica",
]

# --- Prioridade média (bioquímica, função orgânica, urinálise) ---
_CHUNKS_MID: List[str] = [
    "glicemia",
    "hemoglobina glicada",
    "HbA1c",
    "tolerância à glicose",
    "curva glicêmica",
    "insulina",
    "peptídeo C",
    "creatinina",
    "clearance de creatinina",
    "TFG",
    "taxa de filtração glomerular",
    "ureia",
    "ácido úrico",
    "sódio",
    "potássio",
    "cloro",
    "bicarbonato",
    "cálcio",
    "cálcio iônico",
    "fósforo",
    "magnésio",
    "proteínas totais",
    "albumina",
    "globulinas",
    "bilirrubina total",
    "bilirrubina direta",
    "bilirrubina indireta",
    "fosfatase alcalina",
    "FAL",
    "gamma GT",
    "GGT",
    "TGO",
    "AST",
    "TGP",
    "ALT",
    "desidrogenase lática",
    "DHL",
    "CPK",
    "CK-MB",
    "troponina",
    "mioglobina",
    "amilase",
    "lipase",
    "colesterol total",
    "HDL",
    "LDL",
    "triglicerídeos",
    "VLDL",
    "apolipoproteína",
    "homocisteína",
    "ferro sérico",
    "ferritina",
    "transferrina",
    "saturação de transferrina",
    "TIBC",
    "zinco",
    "cobre",
    "vitamina B12",
    "ácido fólico",
    "folato",
    "vitamina D",
    "25 OH vitamina D",
    "paratormônio",
    "PTH",
    "cortisol",
    "ACTH",
    "TSH",
    "T4 livre",
    "T3 livre",
    "anticorpos antitireoide",
    "anti-TPO",
    "anti-tireoglobulina",
    "urina tipo I",
    "EAS",
    "sumário de urina",
    "densidade urinária",
    "pH urinário",
    "proteinúria",
    "glucosúria",
    "cetonúria",
    "nitrito",
    "leucócitos na urina",
    "hemácias dismórficas",
    "cilindros",
    "cristais",
    "urocultura",
    "urinocultura",
    "contagem de colônias",
    "bactéria",
    "fungo",
    "sensibilidade antibiótica",
    "antibiograma",
    "MIC",
    "CMI",
    "concentração inibitória mínima",
    "sensível",
    "intermediário",
    "resistente",
    "breakpoint",
    "urina 24 horas",
    "urina fracionada",
    "clearance de inulina",
    "clearance de amiloide",
    "cistatina C",
    "osmolalidade urinária",
    "osmolalidade sérica",
    "osmol gap",
    "anion gap",
    "relação proteinúria creatinina",
    "proteinúria de Bence Jones",
    "proteinúria seletiva",
    "microalbuminúria",
    "albuminúria",
    "clearance de ureia",
    "cálcio iónico",
    "fósforo tubular máximo",
    "magnésio eritrocitário",
    "piruvato sérico",
    "lactato sérico",
    "lactato venoso",
    "lactato arterial",
    "amônia plasmática",
    "amónia",
    "HOMA-IR",
    "índice HOMA",
    "peptídeo natriurético",
    "BNP",
    "NT-proBNP",
    "hs-troponina",
    "troponina de alta sensibilidade",
    "escore de Wells",
    "CURB-65",
    "estudos do ferro",
    "hepcidina",
    "eritropoietina",
    "serotonina urinária",
    "metanefrinas urinárias",
    "metanefrinas fracionadas",
    "cortisol salivar meia-noite",
    "teste de supressão com dexametasona",
    "IGF-1",
    "IGF BP3",
    "SHBG",
    "AMH",
    "inhibina B",
    "anticorpos anti-receptor de TSH",
    "TRAb",
    "TSH neonatal",
    "bilirrubina neonatal",
    "curva de bilirrubinas",
    "TOTG gravidez",
    "TGO gravidez",
    "TGP gravidez",
    "beta-HCG quantitativo",
    "BHCG",
    "progesterona",
    "estradiol",
    "testosterona livre",
    "testosterona total",
    "DHT",
    "androstenediona",
    "17-OH progesterona",
    "cortisol urinário livre 24 horas",
    "ácido vanilmandélico urinário",
    "VMA",
    "ácido homovanílico urinário",
    "HVA",
    "ácido 5-HIAA urina 24 horas",
    "cromogranina urinária",
    "eletroforese de urina",
    "imunofixação urinária",
    "NMP22",
    "UroVysion",
    "FISH urinário",
    "citologia urinária de alta sensibilidade",
    "vancomicina sérica",
    "digoxina sérica",
    "fenitoína sérica",
    "ácido valpróico sérico",
    "valproato sérico",
    "lítio sérico",
    "litio sérico",
    "carbamazepina sérica",
    "teofilina sérica",
    "ciclosporina sérica",
    "tacrolimus sérico",
    "sirolimus sérico",
    "everolimus sérico",
    "metotrexato sérico",
    "ácido micofenólico",
    "fenobarbital sérico",
    "lamotrigina sérica",
    "oxcarbazepina sérica",
    "levetiracetam sérico",
    "toxicologia urinária",
    "painel de drogas de abuso",
    "cromatografia",
    "espectrometria de massas",
    "vitamina A",
    "vitamina E",
    "vitamina K1",
    "vitamina C",
    "vitamina B1",
    "tiamina",
    "vitamina B6",
    "piridoxina",
    "ácido fólico eritrocitário",
    "folato eritrocitário",
    "selênio sérico",
    "selenio sérico",
    "ceruloplasmina",
    "cobre urinário 24 horas",
    "zinco sérico",
    "alfa-1 antitripsina fenotipo",
    "fenilalanina",
    "PKU",
    "aminoacidúria",
    "perfil de aminoácidos",
    "acilcarnitinas",
    "perfil de acilcarnitinas",
    "G6PD",
    "glicose-6-fosfato desidrogenase",
    "piruvato quinase",
    "PK eritrocitária",
    "eletroforese de hemoglobinas",
    "HbE",
    "HbD",
    "talassemia alfa",
    "talassemia beta",
    "HbA2",
    "HbF",
    "grupo sanguíneo ABO",
    "fator Rh",
    "Du teste",
    "teste de Coombs direto",
    "teste de Coombs indireto",
    "teste do suor",
    "cloreto no suor",
    "elastase fecal",
    "IgE específica",
    "painel alimentar IgE",
    "painel inalatório IgE",
    "teste cutâneo",
    "histamina plasmática",
    "triptase sérica",
    "gasometria arterial",
    "gasometria venosa",
    "hemoximetria",
    "cooximetria",
]

# --- Prioridade alta (hematologia, coagulação, autoimunidade, oncologia, imagem, AP, IHC, genética) ---
_CHUNKS_HIGH: List[str] = [
    "hemograma completo",
    "hemácias",
    "eritrócitos",
    "hemoglobina",
    "hematócrito",
    "VCM",
    "HCM",
    "CHCM",
    "RDW",
    "leucócitos",
    "leucograma",
    "neutrófilos",
    "bastonetes",
    "segmentados",
    "linfócitos",
    "monócitos",
    "eosinófilos",
    "basófilos",
    "plaquetas",
    "volume plaquetário médio",
    "reticulócitos",
    "blastos",
    "mielócitos",
    "metamielócitos",
    "série vermelha",
    "série branca",
    "morfologia eritrocitária",
    "anisocitose",
    "poiquilocitose",
    "normocítica normocrômica",
    "microcitose",
    "macrocitose",
    "hipocromia",
    "anemia",
    "anemia ferropriva",
    "anemia de doença crônica",
    "anemia megaloblástica",
    "leucocitose",
    "leucopenia",
    "neutropenia",
    "neutrofilia",
    "linfopenia",
    "trombocitopenia",
    "trombocitose",
    "plaquetas aumentadas",
    "plaquetas diminuídas",
    "TTPA",
    "tempo de tromboplastina parcial ativada",
    "tempo de protrombina",
    "TP",
    "INR",
    "tempo de sangramento",
    "tempo de coagulação",
    "fibrinogênio",
    "D-dímero",
    "antitrombina III",
    "proteína C",
    "proteína S",
    "fator V de Leiden",
    "anticardiolipina",
    "anticoagulante lúpico",
    "anticorpo antifosfolípide",
    "FAN",
    "padrão nuclear",
    "anti-DNA dupla fita",
    "anti-Sm",
    "anti-RNP",
    "anti-Ro",
    "anti-La",
    "anti-Jo1",
    "anti-Scl70",
    "anti-centrômero",
    "anti-CCP",
    "peptídeo citrulinado cíclico",
    "fator reumatoide",
    "VHS",
    "velocidade de hemossedimentação",
    "proteína C reativa",
    "PCR ultrasensível",
    "imunofixação",
    "eletroforese de proteínas",
    "imunoglobulina G",
    "imunoglobulina A",
    "imunoglobulina M",
    "imunoglobulina E",
    "subclasses de IgG",
    "complemento C3",
    "complemento C4",
    "CH50",
    "pesquisa de sangue oculto",
    "calprotectina fecal",
    "parasitológico de fezes",
    "coprocultura",
    "cultura de escarro",
    "BAAR",
    "GeneXpert",
    "PCR para vírus",
    "CMV",
    "EBV",
    "HBsAg",
    "anti-HBs",
    "anti-HBc total",
    "anti-HBc IgM",
    "HBeAg",
    "anti-HBe",
    "carga viral hepatite B",
    "anti-HCV",
    "carga viral hepatite C",
    "HIV",
    "anti-HIV",
    "Western blot",
    "sífilis",
    "VDRL",
    "FTA-ABS",
    "HTLV",
    "Chagas",
    "IFI para fungos",
    "galactomanano",
    "beta-D-glucano",
    "citomegalovirus",
    "antígeno",
    "marcador tumoral",
    "PSA",
    "PSA livre",
    "CEA",
    "CA 19-9",
    "CA 125",
    "CA 15-3",
    "AFP",
    "beta-HCG",
    "cromogranina A",
    "NSE",
    "enolase neuronal",
    "CYFRA",
    "SCC",
    "tiroglobulina",
    "calcitonina",
    "LDH",
    "PET-CT",
    "PET CT",
    "tomografia por emissão de pósitrons",
    "ressonância magnética",
    "tomografia computadorizada",
    "TC de tórax",
    "TC de abdome",
    "TC de pelve",
    "angiotomografia",
    "ultrassonografia",
    "ultrassom",
    "Doppler",
    "ecocardiograma",
    "radiografia",
    "mamografia",
    "densitometria óssea",
    "cintilografia óssea",
    "estudo contrastado",
    "contraste iodado",
    "contraste gadolínio",
    "lesão ocupando espaço",
    "realce nodular",
    "washout",
    "capsula imperfeita",
    "microcalcificações",
    "BIRADS",
    "LI-RADS",
    "Lung-RADS",
    "RECIST",
    "doença estável",
    "resposta parcial",
    "resposta completa",
    "progressão",
    "anatomopatologia",
    "anatomia patológica",
    "peça cirúrgica",
    "biópsia",
    "citologia",
    "Papanicolau",
    "fragmentos A B C",
    "margens livres",
    "margem comprometida",
    "margem a quente",
    "margem a frio",
    "invasão linfovascular",
    "invasão perineural",
    "necrose",
    "mitoses",
    "índice mitótico",
    "Ki-67",
    "Ki67",
    "graduação histológica",
    "G1",
    "G2",
    "G3",
    "G4",
    "diferenciação",
    "bem diferenciado",
    "moderadamente diferenciado",
    "pouco diferenciado",
    "indiferenciado",
    "carcinoma",
    "adenocarcinoma",
    "carcinoma urotelial",
    "carcinoma de células escamosas",
    "carcinoma neuroendócrino",
    "TNM",
    "estádio",
    "metástase",
    "linfonodo",
    "imunohistoquímica",
    "imunoistoquímica",
    "IHC",
    "estrogênio receptor",
    "progesterona receptor",
    "HER2",
    "FISH",
    "amplificação",
    "PD-L1",
    "TPS",
    "CPS",
    "MLH1",
    "MSH2",
    "MSH6",
    "PMS2",
    "MSI",
    "instabilidade de microssatélites",
    "P53",
    "mutação",
    "wild type",
    "EGFR",
    "KRAS",
    "NRAS",
    "BRAF",
    "ALK",
    "ROS1",
    "NTRK",
    "RET",
    "MET",
    "sequenciamento de nova geração",
    "NGS",
    "painel genético",
    "variante de significado incerto",
    "VUS",
    "variante patogênica",
    "variante provavelmente patogênica",
    "variante benigna",
    "homozigoto",
    "heterozigoto",
    "deleção",
    "duplicação",
    "fusão gênica",
    "translocação",
    "cariótipo",
    "FISH interfasico",
    "PCR em tempo real",
    "carga tumoral",
    "DNA tumoral circulante",
    "biópsia líquida",
    "HLA",
    "tipagem HLA",
    "crossmatch de transplante",
    "anticorpos anti-HLA",
    "locus HLA-A HLA-B HLA-DR",
    "MFI",
    "DSA",
    "Entamoeba histolytica",
    "Ascaris lumbricoides",
    "ancilostomídeos",
    "Necator americanus",
    "Ancylostoma duodenale",
    "Strongyloides stercoralis",
    "Trichuris trichiura",
    "Giardia lamblia",
    "Cryptosporidium",
    "Cyclospora",
    "microsporídios",
    "Aspergillus",
    "galactomanano Aspergillus",
    "criptococo",
    "Cryptococcus neoformans",
    "Histoplasma capsulatum",
    "histoplasmose",
    "Paracoccidioides brasiliensis",
    "paracoccidioidomicose",
    "Coccidioides",
    "Blastomyces dermatitidis",
    "Pneumocystis jirovecii",
    "PCP",
    "cultura fungica",
    "fungo filamentoso",
    "levedura",
    "CMV pp65",
    "antigenemia CMV",
    "CMV viral load",
    "carga viral CMV",
    "EBV VCA IgM",
    "EBV VCA IgG",
    "EBNA IgG",
    "CMV IgM",
    "CMV IgG",
    "HIV genotipagem",
    "genotipo HCV",
    "carga viral HCV",
    "carga viral HBV",
    "anti-HDV",
    "anti-HEV",
    "HEV RNA",
    "parvovirus B19",
    "IgM parvovirus",
    "Zika vírus",
    "dengue",
    "chikungunya",
    "febre amarela",
    "sorologia vacinal",
    "anticorpos vacinais hepatite B",
    "anticorpos vacinais sarampo",
    "anticorpos neutralizantes COVID",
    "COVID anticorpos neutralização",
    "IGRA",
    "Quantiferon",
    "teste tuberculínico",
    "GeneXpert MTB",
    "Xpert MTB",
    "cultura para BAAR",
    "BAAR direto",
    "sorologia Chagas fase aguda",
    "sorologia Chagas fase crônica",
    "IFIX Chagas",
    "leishmaniose",
    "Leishmania",
    "esquistossomose",
    "Schistosoma mansoni",
    "filariose",
    "Wuchereria bancrofti",
    "Loa loa",
    "echinococose",
    "Echinococcus granulosus",
    "Echinococcus multilocularis",
    "tromboelastografia",
    "TEG",
    "ROTEM",
    "coagulação global",
    "fator VIII",
    "fator IX",
    "fator XI",
    "von Willebrand",
    "fator de von Willebrand",
    "ristocetina cofator",
    "antígeno de von Willebrand",
    "proteína S livre",
    "proteína S total",
    "homocisteína trombofilia",
    "trombofilia hereditária",
    "painel de autoanticorpos",
    "anti-SmD1",
    "anti-Ribossomal P",
    "anti-dsDNA",
    "miastenia gravis",
    "anticorpo anti-AChR",
    "anticorpo anti-MuSK",
    "anti-LRP4",
    "encefalite anti-NMDA",
    "anticorpo anti-NMDA",
    "bandas oligoclonais",
    "líquor",
    "LCR",
    "proteínas no LCR",
    "glicose no LCR",
    "cloro no LCR",
    "ADA no LCR",
    "índice IgG líquor soro",
    "citologia liquoral",
    "bacteriologia LCR",
    "cultura LCR",
    "Gram LCR",
    "BAAR LCR",
    "líquido ascítico",
    "líquido pleural",
    "citocentrifugação",
    "adenosina deaminase pleural",
    "ADA pleural",
    "citologia oncótica",
    "LBC colo",
    "teste do pezinho ampliado",
    "triagem neonatal ampliada",
    "VHS por PCR",
    "procalcitonina",
    "antistreptolisina O",
    "ASLO",
    "fator reumatoide",
    "anti-CCP",
    "lactato venoso",
    "lactato arterial",
    "gasometria capilar",
    "oximetria",
    "clearance de amiloide",
    "cadeias leves livres",
    "cadeias leves kappa lambda",
    "proteinúria Bence Jones",
    "imunofixação urina",
    "eletroforese urina",
    "reagente",
    "não reagente",
    "detectável",
    "não detectável",
    "abaixo do limite de quantificação",
    "limite de detecção",
    "positivo",
    "negativo",
    "fracamente positivo",
    "título",
    "títulos",
    "borderline",
    "indeterminado",
    "inconclusivo",
    "recomenda-se correlacionar clinicamente",
]

# Sufixo curto com termos críticos para STT (sempre por último no bloco ``high``),
# para que truncagens agressivas em ``max_chars`` ainda retenham vocabulário essencial.
_PROMPT_HIGH_SUFFIX_ANCHOR = (
    "hemograma hemoglobina leucócitos plaquetas neutrófilos neutropenia "
    "TTPA INR D-dímero imunohistoquímica IHC PD-L1 HER2 EGFR KRAS BRAF "
    "reagente não reagente positivo negativo detectável não detectável "
    "variante patogênica NGS inconclusivo LCR CMV HBsAg galactomanano beta-D-glucano MIC IgE"
)

_WS_RE = re.compile(r"\s+")


def _join_chunks(chunks: List[str]) -> str:
    return " ".join(c.strip() for c in chunks if c and c.strip())


def build_exam_whisper_prompt(max_chars: int = 900) -> str:
    """
    Monta o texto do ``prompt`` do Whisper para laudos/exames em pt-BR.

    Ordem: blocos de **menor** prioridade primeiro, **maior** por último; truncagem
    preserva o final da string (até ``max_chars``). Variável opcional
    ``EXAM_WHISPER_PROMPT_EXTRA`` (conteúdo não sensível) é acrescentada ao **final**,
    antes do truncamento global.

    Nota de produto (OpenAI cookbook *Realtime out-of-band transcription*): lá o
    modelo Realtime gera uma segunda passagem de texto com ``conversation: none``,
    com contexto de sessão e instruções longas. Aqui usamos só o ``prompt`` curto do
    Whisper (limite da API) para viés de vocabulário; uma passagem extra com modelo
    de texto sobre o transcript seria o análogo mais simples para corrigir siglas,
    não exige WebSocket nem Realtime.
    """
    parts: List[str] = []
    low = _join_chunks(_CHUNKS_LOW)
    mid = _join_chunks(_CHUNKS_MID)
    high = _join_chunks(_CHUNKS_HIGH)
    if high:
        high = f"{high} {_PROMPT_HIGH_SUFFIX_ANCHOR}".strip()
    else:
        high = _PROMPT_HIGH_SUFFIX_ANCHOR.strip()
    for block in (low, mid, high):
        if block:
            parts.append(block)

    extra = (os.getenv("EXAM_WHISPER_PROMPT_EXTRA") or "").strip()
    if extra:
        extra = _WS_RE.sub(" ", extra)
        parts.append(extra)

    combined = _WS_RE.sub(" ", " ".join(parts)).strip()
    if max_chars <= 0:
        return ""
    if len(combined) > max_chars:
        combined = combined[-max_chars:].strip()
    return combined
