/** Fila BullMQ: extração estruturada pós-assinatura da evolução */
export const CLINICAL_NOTE_EXTRACTION_QUEUE = 'clinical-note-extraction' as const;

export const LEDGER_OP_CREATE_CLINICAL_EXAM_REQUEST =
  'CREATE_CLINICAL_EXAM_REQUEST' as const;
export const LEDGER_OP_CREATE_MEDICATION = 'CREATE_MEDICATION' as const;
export const LEDGER_OP_CREATE_COMORBIDITY = 'CREATE_COMORBIDITY' as const;
export const LEDGER_OP_UPDATE_PATIENT = 'UPDATE_PATIENT' as const;
export const LEDGER_OP_CREATE_INTERNAL_NOTE = 'CREATE_INTERNAL_NOTE' as const;
export const LEDGER_OP_CREATE_INTERVENTION = 'CREATE_INTERVENTION' as const;
export const LEDGER_OP_CREATE_CANCER_DIAGNOSIS = 'CREATE_CANCER_DIAGNOSIS' as const;
export const LEDGER_OP_UPDATE_CANCER_DIAGNOSIS = 'UPDATE_CANCER_DIAGNOSIS' as const;
export const LEDGER_OP_CREATE_TREATMENT = 'CREATE_TREATMENT' as const;
export const LEDGER_OP_UPDATE_PATIENT_JOURNEY = 'UPDATE_PATIENT_JOURNEY' as const;
export const LEDGER_OP_UPDATE_NAVIGATION_STEP = 'UPDATE_NAVIGATION_STEP' as const;
export const LEDGER_OP_CREATE_COMPLEMENTARY_EXAM = 'CREATE_COMPLEMENTARY_EXAM' as const;
export const LEDGER_OP_CREATE_OBSERVATION = 'CREATE_OBSERVATION' as const;
export const LEDGER_OP_CREATE_PERFORMANCE_STATUS_HISTORY =
  'CREATE_PERFORMANCE_STATUS_HISTORY' as const;
export const LEDGER_OP_CREATE_CLINICAL_PRESCRIPTION_LINE =
  'CREATE_CLINICAL_PRESCRIPTION_LINE' as const;
export const LEDGER_OP_CREATE_QUESTIONNAIRE_RESPONSE =
  'CREATE_QUESTIONNAIRE_RESPONSE' as const;
